VMS.Web/ViewModels/ErrorViewModel.cs
using System;

namespace VMS.Web.ViewModels
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

VMS.Web/Controllers/BaseController.cs
using Microsoft.AspNetCore.Mvc;

namespace VMS.Web.Controllers
{
    public enum AlertType { success, danger, warning, info }

    public class BaseController : Controller
    {
        //Store Alert in TempData Storage only accessable in the next Request
        public void Alert(string message, AlertType type = AlertType.info)
        {
            TempData["Alert.Message"] = message;
            TempData["Alert.Type"] = type.ToString();
        }

    }
}

VMS.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using VMS.Web.ViewModels;

namespace VMS.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

VMS.Web/Controllers/VehicleController.cs
using System;
using VMS.Data.Models;
using VMS.Data.Services;
using Microsoft.AspNetCore.Mvc;
using VMS.Web.ViewModels;

namespace VMS.Web.Controllers
{

    public class VehicleController : BaseController
    {

        private readonly VehicleDbService svc;

        public VehicleController()
        {
            svc = new VehicleDbService();
        }


        //          --- Vehicle Controllers ---          \\          

        //Get /vehicle/index
        public IActionResult Index()
        {
            var vehicles = svc.GetAllVehicles();
            return View(vehicles);
        }

        //Get /vehicle/details/(id)
        public IActionResult Details(int id)
        {
            var vehicle = svc.GetVehicleById(id);

            if(vehicle == null)
            {
                Alert("Vehicle not found", AlertType.warning);
                return RedirectToAction(nameof(Index));
            }

            return View(vehicle);
        }

        //Get /vehicle/create
        public IActionResult Create()
        {
            //render blank form
            return View();
        }

        [HttpPost]
        public IActionResult Create(Vehicle v)
        {
            //verify that the model is valid - passes validation rules defined by Vehicle
            if(ModelState.IsValid)
            {
                //add vehicle to database
                svc.AddVehicle(v);
                Alert("Vehicle successfully created", AlertType.info);
                //redirect to the Index Action
                return RedirectToAction(nameof(Index));
            }
            //redisplay the form for editting as there are validation errors
            return View(v);
        }

        //Get vehicle/edit/id
        public IActionResult Edit(int id)
        {
            //load vehicle using the service
            var v = svc.GetVehicleById(id);

            //check if vehicle returned is not null if so return not found
            if(v == null)
            {
                Alert("Vehicle not found", AlertType.warning);
                return RedirectToAction(nameof(Index));
            }

            //pass vehicle to view for editing
            return View(v);
        }

        //Get vehicle/edit/id
        [HttpPost]
        public IActionResult Edit(Vehicle v, int id)
        {
            //check if model state is valid
            if(ModelState.IsValid)
            {
                //call service to update the vehicle and redirect to index
                svc.UpdateVehicle(id, v);
                Alert("Vehicle Updated", AlertType.info);
                return RedirectToAction(nameof(Index));
            }
            //redisplay the form for editing
            return View(v);
        }

        
        public IActionResult Delete (int id)
        {
            //load vehicle via service
            var vehicle = svc.GetVehicleById(id);
            if(vehicle == null)
            {
                return NotFound();
            }

            //pass vehicle to view for delete confirmation
            return View(vehicle);
        }

        [HttpPost]
        public IActionResult DeleteConfirm(int id)
        {
            //delete vehicle via service 
            svc.DeleteVehicle(id);
            Alert("Vehicle Deleted", AlertType.danger);
            //redirect to the index view 
            return RedirectToAction(nameof(Index));
        }


        //         --- Service Controllers ---          \\

        //Get vehicle/createservice/id
        public IActionResult CreateService(int id)
        {
            var v = svc.GetVehicleById(id);
            
            if(v == null)
            {
                return NotFound();
            }

            //create new Service
            var s = new Service {VehicleId = id};

            //render blank form
            return View(s);
        }


        //Get vehicle/create
        [HttpPost]
        public IActionResult CreateService(Service s)
        {
            if(ModelState.IsValid)
            {
                s.DateOfService = DateTime.Now;
                svc.AddService(s);
                Alert("Service Added", AlertType.info);
                return RedirectToAction(nameof(Index));
            }

            return View(s);
        }
        public IActionResult GetServiceById(int id)
        {
            var service = svc.GetServiceById(id);

            return View(service);
        }

        public IActionResult DeleteService (int id)
        {
            //load service via service
            var service = svc.GetServiceById(id);
            if(service == null)
            {
                return NotFound();
            }

            //pass service to view for delete confirmation
            return View(service);
        }

        [HttpPost]
        public IActionResult DeleteServiceConfirm(int id)
        {
            //delete service via service 
            svc.DeleteService(id);
            Alert("Service Deleted", AlertType.danger);
            //redirect to the index view 
            return RedirectToAction(nameof(Index));
        }

    }
}

VMS.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">    
        <li class="breadcrumb-item active" aria-current="page">Home</li>
    </ol>
</nav>

<div class="jumbotron jumbotron-fluid">
    <div class="container">
        <h1 class="display-4">Vehicle Management System</h1>
        <p class="lead">This is an ASP.NET Core MVC Application Using EntityFramework Core.</p>
        
        <hr class="my-4">

        <p>Provides vehicle fleet management and service record functionality</p>

        <p>Developed as part of COM741 Web Based Application Development Module</p>
        
        <p>(c) - Ulster University </p>
        
    </div>
</div>

VMS.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Project Title</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">VMS.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>              
                        <li>
                            <a class="nav-link text-dark" asp-controller="Vehicle" asp-action="Index">Vehicles</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">

        <!-- Render Alert -->
        <partial name="_RenderAlert"/>

        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            <b>Vehicle Management System - 2020</b>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

VMS.Web/Views/Shared/_RenderAlert.cshtml
@{
   var message = TempData["Alert.Message"] ?? null;
   var type = TempData["Alert.Type"] ?? null;
}

@if (message != null)
{
   <div class="alert alert-@type" role="alert">
      @message
   </div>
}

VMS.Web/Views/Vehicle/Create.cshtml
@model Vehicle

<h3 class="mt-4 mb-4">Create Vehicle</h3>

<form asp-action="Create">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

    <div class="row">

    <div class="form-group col-6">
        <label asp-for="Make" class="control-label"></label>
        <input asp-for="Make" class="form-control"/>
        <span asp-validation-for="Make" class="text-danger"></span>
    </div>

    <div class="form-group col-6">
        <label asp-for="Model" class="control-label"></label>
        <input asp-for="Model" class="form-control"/>
        <span asp-validation-for="Model" class="text-danger"></span>
    </div>

    </div>


    <div class="row">

    <div class="form-group col-3">
        <label asp-for="DateOfReg" class="control-label"></label>
        <input type="date" asp-for="DateOfReg" class="form-control"/>
        <span asp-validation-for="DateOfReg" class="text-danger"></span>
    </div>

    <div class="form-group col-3">
        <label asp-for="Registration" class="control-label"></label>
        <input asp-for="Registration" class="form-control"/>
        <span asp-validation-for="Registration" class="text-danger"></span>
    </div>

    <div class="form-group col-2">
        <label asp-for="EngineSize" class="control-label"></label>
        <input asp-for="EngineSize" class="form-control"/>
        <span asp-validation-for="EngineSize" class="text-danger"></span>
    </div>

    <div class="form-group col-2">
        <label asp-for="Doors" class="control-label"></label>
        <input asp-for="Doors" class="form-control"/>
        <span asp-validation-for="Doors" class="text-danger"></span>
    </div>

    <div class="form-group col-2">
        <label asp-for="C02" class="control-label"></label>
        <input asp-for="C02" class="form-control"/>
        <span asp-validation-for="C02" class="text-danger"></span>
    </div>

    </div>


    <div class="row">

    <div class="form-group col-3">
        <label asp-for="Transmission" class="control-label"></label>
        <input asp-for="Transmission" class="form-control"/>
        <span asp-validation-for="Transmission" class="text-danger"></span>
    </div>

    <div class="form-group col-3">
        <label asp-for="Fuel" class="control-label"></label>
        <input asp-for="Fuel" class="form-control"/>
        <span asp-validation-for="Fuel" class="text-danger"></span>
    </div>

    <div class="form-group col-3">
        <label asp-for="Body" class="control-label"></label>
        <input asp-for="Body" class="form-control"/>
        <span asp-validation-for="Body" class="text-danger"></span>
    </div>

    </div>


    <div class="row">

        <div class="form-group col-9">
        <label asp-for="Photo" class="control-label"></label>
        <input asp-for="Photo" class="form-control"/>
        <span asp-validation-for="Photo" class="text-danger"></span>
        </div>

    </div>

    <div class="form-group">
        <input type="submit" value="Create" class="btn btn-primary"/>
        <a class="btn btn-secondary" asp-action="Index">Cancel</a>
    </div>


</form>

VMS.Web/Views/Vehicle/CreateService.cshtml
@model Service

<h3 class="mt-4 mb-4">Add Service for Vehicle</h3>

<form asp-action="CreateService">

    <input type="hidden" asp-for="VehicleId" class="form-control"/>

    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

    <div class="form-group">
        <label asp-for="EmployeeName" class="control-label"></label>
        <textarea rows="1" asp-for="EmployeeName" class="form-control"></textarea>
        <span asp-validation-for="EmployeeName" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="InvoiceDescription" class="control-label"></label>
        <textarea rows="5" asp-for="InvoiceDescription" class="form-control"></textarea>
        <span asp-validation-for="InvoiceDescription" class="text-danger"></span>
    </div>

    <div class="row">
        <div class="form-group col-6">
            <label asp-for="VehicleMilage" class="control-label"></label>
            <textarea rows="1" asp-for="VehicleMilage" class="form-control"></textarea> 
            <span asp-validation-for="VehicleMilage" class="text-danger"></span>
        </div>
    </div>

    <div class="row">
        <div class="form-group col-6">
            <label asp-for="InvoiceCost" class="control-label"></label>
            <textarea rows="1" asp-for="InvoiceCost" class="form-control"></textarea>
            <span asp-validation-for="InvoiceCost" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <input type="submit" value="Add Service" class="btn btn-primary"/>
        <a class="btn btn-secondary" asp-action="Index">Cancel</a>
    </div>
    
</form>

VMS.Web/Views/Vehicle/Delete.cshtml
@model Vehicle

<!-- Breadcrumb Navigation -->
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a asp-controller="Home" asp-action="Index">Home</a>
        </li>
        <li class="breadcrumb-item" aria-current="page">
            <a asp-controller="Vehicle" asp-action="Index">Vehicles</a>
        </li>
        <li class="breadcrumb-item active" aria-current="page"> 
            Delete
        </li>
    </ol>
</nav>

<h3 class="mt-4 mb-4">Delete Vehicle</h3>

<h4 class="mb-4">Are you sure you want to delete this vehicle?</h4>


<div>

    <!--Display the vehicle details -->
    <dl class="row">
         <dt class="col-sm-3">Make</dt>
        <dd class="col-sm-9">@Model.Make</dd>
        
        <dt class="col-sm-3">Model</dt>
        <dd class="col-sm-9">@Model.Model</dd>
        
        <dt class="col-sm-3">Registration</dt>
        <dd class="col-sm-9">@Model.Registration</dd>
        
        <dt class="col-sm-3">Date Of Registration</dt>
        <dd class="col-sm-9">@Model.DateOfReg.Year</dd>

        <dt class="col-sm-3">Age</dt>
        <dd class="col-sm-9">@Model.Age</dd>

        <dt class="col-sm-3">Fuel Type</dt>
        <dd class="col-sm-9">@Model.Fuel</dd>

        <dt class="col-sm-3">Body Type</dt>
        <dd class="col-sm-9">@Model.Body</dd>

        <dt class="col-sm-3">Transmission</dt>
        <dd class="col-sm-9">@Model.Transmission</dd>

        <dt class="col-sm-3">Engine Size</dt>
        <dd class="col-sm-9">@Model.EngineSize</dd>
        
        <dt class="col-sm-3">No. of Doors</dt>
        <dd class="col-sm-9">@Model.Doors</dd>
    </dl>

    <form asp-action="DeleteConfirm" method="POST">
        <input type="hidden" name="id" value=@Model.VehicleId />
        
        <div class="form-group">
            <input type="submit" value="Delete" class="btn btn-danger"/>
            <a class="btn btn-secondary" asp-action="Index">Cancel</a>
        </div>
    </form>

</div>

VMS.Web/Views/Vehicle/DeleteService.cshtml
@model Service

<h3 class="mt-4 mb-4">Delete Service</h3>

<h4 class="mb-4">Are you sure you want to delete service for this vehicle?</h4>

<div>

    <!--Display the service details -->
    <dl class="row">
         <dt class="col-sm-3">Staff</dt>
        <dd class="col-sm-9">@Model.EmployeeName</dd>
        
        <dt class="col-sm-3">Date</dt>
        <dd class="col-sm-9">@Model.DateOfService.Year</dd>
        
        <dt class="col-sm-3">Description</dt>
        <dd class="col-sm-9">@Model.InvoiceDescription</dd>
    </dl>


    <form asp-action="DeleteServiceConfirm" method="POST">
        <input type="hidden" name="id" value=@Model.ServiceId />
        
        <div class="form-group">
            <input type="submit" value="Delete" class="btn btn-danger"/>
            <a class="btn btn-secondary" asp-action="Index">Cancel</a>
        </div>
    </form>

</div>

VMS.Web/Views/Vehicle/Details.cshtml
@{
    ViewData["Title"] = "Vehicle Details";
}

@model Vehicle

<!-- Breadcrumb Navigation -->
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a asp-controller="Home" asp-action="Index">Home</a>
        </li>
        <li class="breadcrumb-item" aria-current="page">
            <a asp-controller="Vehicle" asp-action="Index">Vehicles</a>
        </li>
        <li class="breadcrumb-item active" aria-current="page"> 
            Details
        </li>
    </ol>
</nav>

<h3 class="mt-4 mb-4">Vehicle Details</h3>

<div class="container">
    <div class="row">
    <div class="col-7">
        <dl class="row">
                <dt class="col-sm-3">Make</dt>
                <dd class="col-sm-9">@Model.Make</dd>
                
                <dt class="col-sm-3">Model</dt>
                <dd class="col-sm-9">@Model.Model</dd>
                
                <dt class="col-sm-3">Year</dt>
                <dd class="col-sm-9">@Model.DateOfReg.Year</dd>
                
                <dt class="col-sm-3">Registration</dt>
                <dd class="col-sm-9">@Model.Registration</dd>

                <dt class="col-sm-3">Transmission</dt>
                <dd class="col-sm-9">@Model.Transmission</dd>

                <dt class="col-sm-3">CO2 Rating</dt>
                <dd class="col-sm-9">@Model.C02</dd>

                <dt class="col-sm-3">Fuel Type</dt>
                <dd class="col-sm-9">@Model.Fuel</dd>

                <dt class="col-sm-3">Body Type</dt>
                <dd class="col-sm-9">@Model.Body</dd>

                <dt class="col-sm-3">Doors</dt>
                <dd class="col-sm-9">@Model.Doors</dd>

                <dt class="col-sm-3">CC</dt>
                <dd class="col-sm-9">@Model.EngineSize</dd>
        </dl> <!-- row -->
    </div> <!-- col-7 -->

    <div class="col-5">
        <img class="img-fluid img-thumbnail border-dark" src="@Model.Photo"> 


        <a class="btn btn-danger btn-sm mt-2" asp-action="Index">
            <b>Vehicles </b>
            <svg class="bi bi-card-list" width="1.5em" height="1.5em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M14.5 3h-13a.5.5 0 00-.5.5v9a.5.5 0 00.5.5h13a.5.5 0 00.5-.5v-9a.5.5 0 00-.5-.5zm-13-1A1.5 1.5 0 000 3.5v9A1.5 1.5 0 001.5 14h13a1.5 1.5 0 001.5-1.5v-9A1.5 1.5 0 0014.5 2h-13z" clip-rule="evenodd"/>
                <path fill-rule="evenodd" d="M5 8a.5.5 0 01.5-.5h7a.5.5 0 010 1h-7A.5.5 0 015 8zm0-2.5a.5.5 0 01.5-.5h7a.5.5 0 010 1h-7a.5.5 0 01-.5-.5zm0 5a.5.5 0 01.5-.5h7a.5.5 0 010 1h-7a.5.5 0 01-.5-.5z" clip-rule="evenodd"/>
                <circle cx="3.5" cy="5.5" r=".5"/>
                <circle cx="3.5" cy="8" r=".5"/>
                <circle cx="3.5" cy="10.5" r=".5"/>
            </svg>
        </a>

        <a class="btn btn-primary btn-sm mt-2" asp-action="Edit" asp-route-id="@Model.VehicleId">
            <b>Edit </b>
            <svg class="bi bi-pencil-square" width="1.5em" height="1.5em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path d="M15.502 1.94a.5.5 0 010 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 01.707 0l1.293 1.293zm-1.75 2.456l-2-2L4.939 9.21a.5.5 0 00-.121.196l-.805 2.414a.25.25 0 00.316.316l2.414-.805a.5.5 0 00.196-.12l6.813-6.814z"/>
                <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 002.5 15h11a1.5 1.5 0 001.5-1.5v-6a.5.5 0 00-1 0v6a.5.5 0 01-.5.5h-11a.5.5 0 01-.5-.5v-11a.5.5 0 01.5-.5H9a.5.5 0 000-1H2.5A1.5 1.5 0 001 2.5v11z" clip-rule="evenodd"/>
            </svg>
        </a>

    </div> <!-- Car Photo & buttons -->

</div> <!-- row -->
</div> <!-- container -->

<!-- Partial rendering of vehicles services --> 
<partial name="_Services" />

<!-- Create Service Button -->
<div>
     <a asp-action="CreateService" asp-route-id=@Model.VehicleId class="btn btn-primary btn-sm">Add Service</a>
</div>

VMS.Web/Views/Vehicle/Edit.cshtml
@model Vehicle

<!-- Breadcrumb Navigation -->
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a asp-controller="Home" asp-action="Index">Home</a>
        </li>
        <li class="breadcrumb-item" aria-current="page">
            <a asp-controller="Vehicle" asp-action="Index">Vehicles</a>
        </li>
        <li class="breadcrumb-item active" aria-current="page"> 
            Details
        </li>
    </ol>
</nav>

<h3 class="mt4 mb4">Edit Vehicle</h3>


<form asp-action="Edit">

 <div asp-validation-summary="ModelOnly" class="text-danger"></div>
 <input type="hidden" asp-for="VehicleId" class="form-control"/>


    <div class="row">

        <div class="form-group col-6">
                <label asp-for="Make" class="control-label"></label>
                <input asp-for="Make" class="form-control"/>
                <span asp-validation-for="Make" class="text-danger"></span>
        </div>

        <div class="form-group col-6">
                <label asp-for="Model" class="control-label"></label>
                <input asp-for="Model" class="form-control"/>
                <span asp-validation-for="Model" class="text-danger"></span>
        </div>

    </div> <!-- first row -->

    <div class="row">

        <div class="form-group col-3">
                <label asp-for="DateOfReg" class="control-label"></label>
                <input type="date" asp-for="DateOfReg" class="form-control"/>
                <span asp-validation-for="DateOfReg" class="text-danger"></span>
        </div>

        <div class="form-group col-3">
                <label asp-for="Registration" class="control-label"></label>
                <input asp-for="Registration" class="form-control"/>
                <span asp-validation-for="Registration" class="text-danger"></span>
        </div>

        <div class="form-group col-2">
                <label asp-for="EngineSize" class="control-label"></label>
                <input asp-for="EngineSize" class="form-control"/>
                <span asp-validation-for="EngineSize" class="text-danger"></span>
        </div>

        <div class="form-group col-2">
                <label asp-for="Doors" class="control-label"></label>
                <input asp-for="Doors" class="form-control"/>
                <span asp-validation-for="Doors" class="text-danger"></span>
        </div>

        <div class="form-group col-2">
                <label asp-for="C02" class="control-label"></label>
                <input asp-for="C02" class="form-control"/>
                <span asp-validation-for="C02" class="text-danger"></span>
        </div>

    </div> <!-- second row -->

    <div class="row">

        <div class="form-group col-4">
                <label asp-for="Transmission" class="control-label"></label>
                <input asp-for="Transmission" class="form-control"/>
                <span asp-validation-for="Transmission" class="text-danger"></span>
        </div>

        <div class="form-group col-4">
                <label asp-for="Fuel" class="control-label"></label>
                <input asp-for="Fuel" class="form-control"/>
                <span asp-validation-for="Fuel" class="text-danger"></span>
        </div>

        <div class="form-group col-4">
                <label asp-for="Body" class="control-label"></label>
                <input asp-for="Body" class="form-control"/>
                <span asp-validation-for="Body" class="text-danger"></span>
        </div>

    </div><!--third row -->


    <div class="row">
            <div class="form-group col-6">
                <label asp-for="Photo" class="control-label"></label>
                <input asp-for="Photo" class="form-control"/>
                <span asp-validation-for="Photo" class="text-danger"></span>
            </div>
    </div> <!-- forth row -->

    <div class="form-group">
        <input type ="submit" value="Save" class="btn btn-primary"/>
        <a class="btn btn-secondary" asp-action="Index">Cancel</a>
    </div> 


</form>

VMS.Web/Views/Vehicle/_Services.cshtml
@model Vehicle

<!-- Service List for Vehicle -->
<h3>Service History</h3>
<table class="table table-sm table-striped">
    <thead class="thead-dark">
        <tr>
            <th>Date</th>
            <th>Invoice Details</th>
            <th>Staff</th>
            <th>Cost</th>
            <th>Actions</th>
        </tr>    
    </thead>

    <tbody>

       @foreach (var s in Model.Services)
       {
           <tr>
               <td>@s.DateOfService.ToShortDateString()</td>
               <td>@s.InvoiceDescription</td>
               <td>@s.EmployeeName</td>
               <td>£@s.InvoiceCost.ToString("0.00")</td>
               <td>
                   <a asp-action="DeleteService" asp-route-id=@s.ServiceId>
                        <svg class="bi bi-trash" width="1.5em" height="1.5em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path d="M5.5 5.5A.5.5 0 016 6v6a.5.5 0 01-1 0V6a.5.5 0 01.5-.5zm2.5 0a.5.5 0 01.5.5v6a.5.5 0 01-1 0V6a.5.5 0 01.5-.5zm3 .5a.5.5 0 00-1 0v6a.5.5 0 001 0V6z"/>
                            <path fill-rule="evenodd" d="M14.5 3a1 1 0 01-1 1H13v9a2 2 0 01-2 2H5a2 2 0 01-2-2V4h-.5a1 1 0 01-1-1V2a1 1 0 011-1H6a1 1 0 011-1h2a1 1 0 011 1h3.5a1 1 0 011 1v1zM4.118 4L4 4.059V13a1 1 0 001 1h6a1 1 0 001-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z" clip-rule="evenodd"/>
                        </svg>
                   </a>
                </td>
           </tr>
       }

    </tbody>

</table> 